version: "3.8"
services:
  backend:
    build: ./backend
    image: "${BACKEND_IMAGE}:${IMAGE_TAG}"
    ports:
      - "${BACKEND_PORT}:8000"
    env_file: .env
  frontend:
    build: ./frontend
    image: "${FRONTEND_IMAGE}:${IMAGE_TAG}"
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - REACT_APP_API_URL=http://localhost:${BACKEND_PORT}
networks:
  default:
    name: text-evaluator-net
