name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

env:
  DOCKER_REGISTRY: ghcr.io/lisa086
  BACKEND_IMAGE:   text-evaluator-backend
  FRONTEND_IMAGE:  text-evaluator-frontend
  IMAGE_TAG:       ${{ github.sha }}
  REGISTRY_USER:   ${{ github.actor }}
  REGISTRY_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.BACKEND_IMAGE }}:latest
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.BACKEND_IMAGE }}:${{ github.sha }}

      - name: Build & push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.FRONTEND_IMAGE }}:latest
            ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.FRONTEND_IMAGE }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH (with fallback compose)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            if [ ! -d "${{ secrets.DEPLOY_PATH }}" ]; then
              git clone https://github.com/Lisa086/text-evaluator-devops.git ${{ secrets.DEPLOY_PATH }}
            fi
            cd ${{ secrets.DEPLOY_PATH }}
            git pull origin main

            if command -v docker-compose >/dev/null 2>&1; then
              docker-compose pull
              docker-compose up -d --remove-orphans
            else
              docker compose pull
              docker compose up -d --remove-orphans
            fi
