name: CI/CD Pipeline

on:
  push:
    branches: ['main']
    tags: ['v*.*.*']

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ghcr.io/lisa086/text-evaluator-backend:${{ env.TAG }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/lisa086/text-evaluator-frontend:${{ env.TAG }}

  test-locally:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Prepare .env
        run: cp .env.example .env

      - name: Pull images
        run: docker compose pull

      - name: Start services
        run: docker compose up -d

      - name: Smoke test backend
        run: curl --fail http://localhost:8000/health

      - name: Smoke test frontend
        run: curl --fail http://localhost:3000

      - name: Tear down
        run: docker compose down
